//! Serde round-trip with refined domain newtypes.
//!
//! A user struct embeds two domain newtypes (`UserName` and `Age`),
//! each generated by one `refinement!` error-block declaration. With
//! whittle's `serde` feature on, the macro emits transparent
//! `Serialize` / `Deserialize` impls forwarding to the inner
//! `Refined`, which:
//!
//! - **Serialize** writes the bare inner value (no rule-marker
//!   noise on the wire).
//! - **Deserialize** runs the raw value through the rule — and
//!   because the inner rule is `MapErr<..., UserNameError>`, a
//!   rejection at ingress renders the **domain** error's `Display`
//!   text, the same diagnostics `try_new` returns. The previous
//!   hand-written `#[serde(transparent)]` derive surfaced the raw
//!   rule text instead ("character count 2 not in admissible
//!   range"); the declaration below upgrades the ingress message to
//!   "user name length 2 not in 3..=32".
//!
//! Headline patterns demonstrated:
//!
//! 1. **The newtype is the domain.** Public struct fields are
//!    `UserName` and `Age`, not raw `Refined<String, LenChars<...>>`.
//!    The `Refined` carrier is an implementation detail.
//! 2. **Flat domain errors.** Each newtype owns a flat enum
//!    (`UserNameError`, `AgeError`) generated from its declaration,
//!    with hand-rolled `Display` + `core::error::Error` impls — no
//!    error-derive macro involved.
//! 3. **`deny_unknown_fields` is the outer struct's
//!    responsibility.** `Refined<T, R>` has no visibility into the
//!    outer field map, so the attribute lives on `UserInput`.

#![expect(
    clippy::unwrap_used,
    clippy::disallowed_methods,
    reason = "integration test: unwrap keeps the focus on the API"
)]

use core::error::Error;

use serde::{Deserialize, Serialize};
use whittle::primitive::{LenChars, NumericError, StringError, Within};
use whittle::refinement;

// ─── UserName: 3..=32 character display name. ────────────────

refinement! {
    /// Nominal display-name newtype. The inner `Refined<...>` field is
    /// private so callers cannot bypass `try_new`.
    #[derive(Debug, Clone, PartialEq, Eq, Hash)]
    pub UserName: String, LenChars<3, 32>;
    impl Display;

    /// Flat domain error for `UserName`.
    error StringError => pub UserNameError {
        /// Length (in characters) outside `3..=32`.
        StringError::CharCountOutOfRange { actual } => Length {
            /// Observed character count of the offending string.
            actual: usize,
        }: "user name length {actual} not in 3..=32",
        // `LenChars` only emits `CharCountOutOfRange`.
        unreachable StringError::ByteLenOutOfRange { .. }
            | StringError::Empty
            | StringError::BadChar { .. }
            | StringError::BadFirstChar
            | StringError::BadHexLength { .. },
    }
}

// ─── Age: 0..=150 years. ─────────────────────────────────────

refinement! {
    /// Nominal age newtype. The inner `Refined<...>` is private.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
    pub Age: u8, Within<0, 150>;
    impl Display;

    /// Flat domain error for `Age`. `Within` emits only
    /// `OutOfRange`, so the mapping is total and there is no
    /// `unreachable` arm.
    error NumericError => pub AgeError {
        /// Value outside `0..=150`.
        NumericError::OutOfRange { value } => OutOfRange {
            /// Offending value widened losslessly into `i128`.
            value: i128,
        }: "age {value} not in 0..=150",
    }
}

// ─── Outer payload. `deny_unknown_fields` is the struct's job. ─

#[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
struct UserInput {
    name: UserName,
    age: Age,
}

#[test]
fn user_input_round_trips_through_json_transparently() {
    // Round-trip an admissible value.
    let original = UserInput {
        name: UserName::try_new("Alice".to_string()).unwrap(),
        age: Age::try_new(30).unwrap(),
    };
    let json = serde_json::to_string(&original).unwrap();
    // The emitted `Serialize` forwards to the inner value, so the
    // newtype disappears on the wire — the JSON contains only the
    // inner values.
    assert_eq!(json, r#"{"name":"Alice","age":30}"#);
    let parsed: UserInput = serde_json::from_str(&json).unwrap();
    assert_eq!(parsed, original);
    assert_eq!(parsed.name.as_inner(), "Alice");
    assert_eq!(*parsed.age.as_inner(), 30);
}

#[test]
fn deserialize_rejects_invalid_name_with_domain_text() {
    // Reject at deserialize time: name is too short (fails
    // `LenChars<3, 32>`). The `MapErr` rule maps the rejection
    // before serde renders it, so the ingress message is the domain
    // `Display` text — not the raw rule text ("character count 2
    // not in admissible range") the old `#[serde(transparent)]`
    // derive surfaced.
    let bad_name = serde_json::from_str::<UserInput>(r#"{"name":"AB","age":30}"#).unwrap_err();
    assert_eq!(
        bad_name.to_string(),
        "user name length 2 not in 3..=32 at line 1 column 12",
    );
}

#[test]
fn deserialize_rejects_out_of_range_age_with_domain_text() {
    // Reject at deserialize time: age out of range. Same mechanism —
    // the parsed `u8` runs through `Within<0, 150>` and the mapping
    // renders the domain text at ingress.
    let bad_age = serde_json::from_str::<UserInput>(r#"{"name":"Alice","age":200}"#).unwrap_err();
    assert_eq!(
        bad_age.to_string(),
        "age 200 not in 0..=150 at line 1 column 26",
    );
}

#[test]
fn deny_unknown_fields_rejects_extra_keys_on_outer_struct() {
    // Reject at deserialize time: unknown field.
    // `deny_unknown_fields` lives on `UserInput` because the outer
    // type controls its own field map — `Refined` has no hook for
    // this policy.
    let unknown_field: Result<UserInput, _> =
        serde_json::from_str(r#"{"name":"Alice","age":30,"email":"x"}"#);
    unknown_field.unwrap_err();
}

#[test]
fn flat_domain_errors_implement_display_and_error_traits() {
    // The flat domain errors implement `Display` and `Error`, so
    // they work with `?`, `anyhow`, and stdlib error machinery —
    // both impls generated from the declarations' per-arm literals,
    // no derive macro involved.
    let _: &dyn Error = &UserNameError::Length { actual: 1 };
    let _: &dyn Error = &AgeError::OutOfRange { value: 200 };
    assert_eq!(
        UserNameError::Length { actual: 1 }.to_string(),
        "user name length 1 not in 3..=32",
    );
}
