[graph]
all-features = false
no-default-features = false

[advisories]
ignore = []

[licenses]
allow = [
  "0BSD",
  "Apache-2.0 WITH LLVM-exception",
  "Apache-2.0",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "CDLA-Permissive-2.0",
  "ISC",
  "MIT",
  "Unicode-3.0",
  "Unlicense",
  "Zlib",
]
exceptions = []

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
